name: test
on: push
jobs:
  build_code_ubuntu_x64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: bash build.sh
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: binaries_linux_x64
        path: |
          cpp/naive
          cpp/sieve
          cpp/segmented
  build_code_ubuntu_arm:
    runs-on: guineapi
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: bash build.sh
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: binaries_linux_arm
        path: |
          cpp/naive
          cpp/sieve
          cpp/segmented
  build_code_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v1.3
    - name: Build
      run: ./build.ps1
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: binaries_windows
        path: |
          cpp/naive.exe
          cpp/sieve.exe
          cpp/segmented.exe
  benchmark:
    needs: build_code_ubuntu_x64
    runs-on: furiosa
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v3
      with:
        name: binaries_linux_x64
    - name: Run
      run: bash run.sh
