name: test
on: push
jobs:
  build_code_ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir build-dir
        cd build-dir
        cmake ..
        make
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: binaries_linux
        path: |
          build-dir
          !build-dir/*make*
          !build-dir/*Make*
  # build_code_raspberry_pi:
  #   runs-on: guineapi
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build
  #     run: |
  #       mkdir build-dir
  #       cd build-dir
  #       cmake ..
  #       make
  #   - name: Upload files
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: binaries_arm
  #       path: |
  #         build-dir
  #         !build-dir/*make*
  #         !build-dir/*Make*
  # build_windows_docker:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build Image
  #     run: |
  #       docker build -t run_environment_win_x64 -f run_environment_win_x64.dockerfile .
  #   - name: Push to Docker
  #     run: |
  #       echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  #       docker tag run_environment_win_x64 gaebor/primes-github-runners:run_environment_win_x64
  #       docker push gaebor/primes-github-runners:run_environment_win_x64
  build_code_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v1.3
    - name: Build
      run: |
        cmake .
        msbuild /p:Configuration=Release primes.sln
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: binaries_windows
        path: |
          Release/*.exe
  benchmark:
    needs: build_code_ubuntu
    runs-on: furiosa
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v3
      with:
        name: binaries_linux
    - name: Prerequisites
      run: python3 -m pip install pyopencl[pocl] tqdm
    - name: Run
      run: |
        python3 pyopencl/primes.py -h
        chmod u+x ./*
        bash benchmark.sh
  # benchmark_raspberry_pi:
  #   needs: build_code_raspberry_pi
  #   runs-on: guineapi
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/download-artifact@v3
  #     with:
  #       name: binaries_arm
  #   - name: Prerequisites
  #     run: python -m pip install pyopencl[pocl] tqdm
  #   - name: Run
  #     run: |
  #       python primes.py -h
  #       chmod u+x ./*
  #       bash benchmark.sh
  # test_win:
  #   needs: build_code_windows
  #   runs-on: MANGORLO
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/download-artifact@v3
  #     with:
  #       name: binaries_windows
  #   - name: Prerequisites
  #     run: python -m pip install pyopencl tqdm
  #   - name: Run
  #     shell: cmd
  #     run: |
  #       python primes.py -h
  #       segmented.exe -h
  test_macos:
    runs-on: gaeborsMBP
    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: |
        brew install -y python
        python -m ensurepip --upgrade
        python -m pip install pyopencl[pocl] tqdm
        python pyopencl/primes.ph -h
