name: test
on: push
jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: python -m pip install black pylint
    - name: Formatting
      run: black --check --line-length=99 --skip-string-normalization primes.py
    - name: Lint
      run: pylint --enable-all-extensions --fail-under 10 --disable=C0114,C0115,C0116,E0401 primes.py
  build_code_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir build-dir
        cd build-dir
        cmake ..
        make
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: binaries_linux
        path: |
          build-dir
          !build-dir/*make*
          !build-dir/*Make*
  build_code_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && cl.exe /W4 /O2 /Ob2 /MT /D_CRT_SECURE_NO_DEPRECATE /DNDEBUG /DNODEBUG /DWIN32 /EHsc /TP segmented.cpp /I. /link ws2_32.lib shell32.lib /OUT:segmented.exe
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: binaries_windows
        path: |
          *.exe
  benchmark:
    needs: build_code_ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v3
      with:
        name: binaries_linux  
    - name: Run
      run: |
        chmod u+x ./*
        bash benchmark.sh
  test_win:
    needs: build_code_windows
    runs-on: MANGORLO
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: binaries_windows
    - name: Run
      shell: cmd
      run: |
        segmented.exe
