name: test
on: push
jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: python -m pip install black pylint
    - name: Formatting
      run: black --check --line-length=99 --skip-string-normalization primes.py
    - name: Lint
      run: pylint --enable-all-extensions --fail-under 10 --disable=C0114,C0115,C0116,E0401 primes.py
  build_code_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir build-dir
        cd build-dir
        cmake ..
        make
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: binaries_linux
        path: |
          build-dir
          !build-dir/*make*
          !build-dir/*Make*
          primes.py
  build_code_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v1.3
    - name: Build
      run: |
        cmake .
        msbuild /p:Configuration=Release primes.sln
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: binaries_windows
        path: |
          Release/*.exe
          primes.py
  benchmark:
    needs: build_code_ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: binaries_linux  
    - name: Run
      run: |
        chmod u+x ./*
        bash benchmark.sh
  test_win:
    needs: build_code_windows
    runs-on: MANGORLO
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: binaries_windows
    - name: Run
      run: |
        python primes.py -h
